/**
 * ContextMetricsSection - Token usage, cache efficiency, and context compaction tracking
 */

import { LightBulbIcon } from '@heroicons/react/24/outline'
import { MetricCard } from '../MetricCard.js'
import { MetricSection } from '../MetricSection.js'
import type { SessionMetricsUI } from '../MetricsOverview.js'

interface ContextMetricsSectionProps {
  context: SessionMetricsUI['context']
}

export function ContextMetricsSection({ context }: ContextMetricsSectionProps) {
  if (!context || context.totalInputTokens === undefined || context.totalInputTokens === null) {
    return null
  }

  return (
    <MetricSection
      title="Context Management"
      subtitle="Token usage, cache efficiency, and context compaction tracking"
      icon={<LightBulbIcon />}
    >
      <div className="space-y-4">
        {/* Token Usage Overview */}
        <div className="grid grid-cols-3 gap-3 md:gap-4">
          <MetricCard
            label="Total Input Tokens"
            value={context.totalInputTokens}
            tooltip="Sum of all input tokens sent to API across the entire session"
          />
          <MetricCard
            label="Total Output Tokens"
            value={context.totalOutputTokens}
            tooltip="Sum of all tokens generated by the AI (responses)"
          />
          <MetricCard
            label="Compaction Events"
            value={context.compactEventCount}
            tooltip="Number of times the session hit context limits and required compaction"
            metricId="compaction-events"
          />
        </div>

        <div className="divider text-sm">Context Status</div>

        {/* Context Details */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 md:gap-4">
          <MetricCard
            label="Current Context"
            value={context.contextLength}
            suffix=" tokens"
            tooltip="Current context window size from most recent API call"
          />
          <MetricCard
            label="Context Window"
            value={context.contextWindowSize}
            suffix=" tokens"
            tooltip="Model's maximum context capacity (200K tokens)"
          />
          <MetricCard
            label="Context Usage"
            value={
              context.contextUtilizationPercent
                ? Number.parseFloat(context.contextUtilizationPercent.toString())
                : undefined
            }
            type="percentage"
            tooltip="Current context as percentage of max context window"
            metricId="context-utilization"
          />
          <MetricCard
            label="Avg Tokens/Message"
            value={
              context.avgTokensPerMessage
                ? Number.parseFloat(context.avgTokensPerMessage.toString())
                : undefined
            }
            tooltip="Average input tokens per message"
          />
        </div>
      </div>
    </MetricSection>
  )
}
